required = [
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/informer-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "github.com/onsi/ginkgo/ginkgo",
]


# dep needs the following to be overrides to convince it that CR can work with these library versions,
# because it doesn't understand the "kubernetes-x.y.z" tags.
[[override]]
  name = "k8s.io/api"
  branch = "master"

[[override]]
  name = "k8s.io/apimachinery"
  branch = "master"

[[override]]
  name = "k8s.io/client-go"
  branch = "master"

[[constraint]]
  name = "k8s.io/component-base"
  branch = "master"

[[constraint]]
  name = "k8s.io/code-generator"
  branch = "master"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  branch = "master"

[[override]]
  name = "k8s.io/apiserver"
  branch = "master"

[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "v21.3.0"

[[constraint]]
  name = "github.com/digitalocean/godo"
  version = "v1.6.0"

# Use a custom version of the library with https://github.com/openshift/generic-admission-server/pull/21
[[constraint]]
  name = "github.com/openshift/generic-admission-server"
  branch = "release-1.14"

[[constraint]]
  name = "github.com/hashicorp/vault"
  version = "v0.9.3"

# Use the GitHub mirror of goautoneg to save issues with bitbucket being down
[[override]]
  name = "bitbucket.org/ww/goautoneg"
  revision = "a547fc61f48d567d5b4ec6f8aee5573d8efce11d"
  source = "https://github.com/munnerz/goautoneg.git"

[[constraint]]
  name = "sigs.k8s.io/controller-runtime"
  revision = "e8e2826de704fcb1d380d42d79d70abaf9186cee"
  source = "https://github.com/munnerz/controller-runtime.git"

### Overrides for transitive kubernetes dependencies
### These should be updated whenever we bump the kubernetes version we depend on
[[override]]
  name = "k8s.io/gengo"
  revision = "51747d6e00da1fc578d5a333a93bb2abcbce7a95"

[[override]]
  name = "google.golang.org/grpc"
  # version 1.13.0
  revision = "168a6198bcb0ef175f7dacec0b8691fc141dc9b8"

[[override]]
  name = "k8s.io/kube-openapi"
  revision = "c59034cc13d587f5ef4e85ca0ade0c1866ae8e1d"

[[override]]
  name = "github.com/golang/protobuf"
  # version 1.1.0
  revision = "b4deda0973fb4c70b50d226b1af49f3da59f5265"

[[override]]
  name = "google.golang.org/genproto"
  revision = "09f6ed296fc66555a25fe4ce95173148778dfa85"

[[override]]
  name = "github.com/json-iterator/go"
  revision = "ab8a2e0c74be9d3be70b3184d9acc634935ded82"

[[override]]
  name = "github.com/Azure/go-autorest"
  revision = "ea233b6412b0421a65dc6160e16c893364664a95"

[prune]
  unused-packages = true
  go-tests = true
  [[prune.project]]
    name = "github.com/hashicorp/vault"
    non-go = true
  [[prune.project]]
    name = "github.com/prometheus/procfs"
    non-go = true
  [[prune.project]]
    name = "github.com/hashicorp/go-rootcerts"
    non-go = true
  [[prune.project]]
    name = "k8s.io/code-generator"
    unused-packages = false
  [[prune.project]]
    name = "k8s.io/kube-openapi"
    unused-packages = false
